def draw(mistakes):
    match mistakes:
        case 0:
            print("     _")
            print("     ")
            print("     ")
            print("       ")
            print("       ")
            print(" ")
        case 1:
            print("      ")
            print("|    ")
            print("|    ")
            print("|      ")
            print("|      ")
            print("|")
        case 2:
            print("______")
            print("|    ")
            print("|    ")
            print("|      ")
            print("|      ")
            print("|")
        case 3:
            print("______")
            print("|    ")
            print("|   O")
            print("|      ")
            print("|      ")
            print("|")
        case 4:
            print("______")
            print("|    ")
            print("|   O")
            print("|   |  ")
            print("|      ")
            print("|")
        case 5:
            print("______")
            print("|    ")
            print("|   O")
            print("|  /|  ")
            print("|      ")
            print("|")
        case 6:
            print("______")
            print("|    ")
            print("|   O")
            print("|  /|\\")
            print("|      ")
            print("|")
        case 7:
            print("______")
            print("|    ")
            print("|   O")
            print("|  /|\\")
            print("|  /   ")
            print("|")
        case 8:
            print("______")
            print("|    ")
            print("|   O")
            print("|  /|\\")
            print("|  / \\")
            print("|")
        case 9:
            print("______")
            print("|   |")
            print("|   O")
            print("|  /|\\")
            print("|  / \\")
            print("|")
